### ISSUE TITLE
.NetStandard and Console demo

### ISSUE THREAD

**Issue by NicoCG** [codingseb/TranslateMe#5]
Hello, could you kindly migrate this project to .NetStandard and if possible provide us with a console demo of this library?

**Comment by codingseb** [comment]
Hello, I will look how to do this. For now I only work in .net Frameworks because I usually do WPF projects.
If I migrate,I'll have to split the nuget package into 2 parts because the current package contains all the WPFs stuffs and WPF is only .Net Framework compatible.
